language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8
services:
  - postgresql
addons:
  postgresql: "9.3"
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2
before_script:
  - psql -c "CREATE USER enthub WITH PASSWORD 'enthub';" -U postgres
  - psql -c "ALTER USER enthub CREATEDB;" -U postgres
  - cd EntHub/
script:
  - python manage.py test --verbosity=2
