language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2
# command to run tests
before_script:
  - psql -c "CREATE USER enthub WITH PASSWORD 'enthub';" -U postgres
  - psql -c "ALTER USER enthub CREATEDB;" -U postgres
script:
  - python EntHub/manage.py test
