language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8
services:
  - postgresql
addons:
  postgresql: "9.3"
  firefox: "49.0.2"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - echo $PATH
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2
  - pip install selenium==3.0.0
  - pip install coverage
before_script:
  - psql -c "CREATE USER enthub WITH PASSWORD 'enthub';" -U postgres
  - psql -c "ALTER USER enthub CREATEDB;" -U postgres
  - cd EntHub/
script:
  - coverage run --source='.' manage.py test --verbosity=2
after_script:
  - coverage report
