language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8
services:
  - postgresql
addons:
  postgresql: "9.4"
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2
before_script:
  - psql -c "CREATE USER enthub WITH PASSWORD 'enthub';" -U postgres
  - psql -c "ALTER USER enthub CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE enthub_test;" -U postgres
test:
  adapter: postgresql
  database: enthub_test
script:
  - python EntHub/manage.py test
