# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-22 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20170518_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='originId',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='comic',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='originId',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='comicseries',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comicseries',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comicseries',
            name='originId',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='dlc',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dlc',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dlc',
            name='originId',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='originId',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='movie',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='originId',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='series',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='originId',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='bookinvolvement',
            name='role',
            field=models.CharField(choices=[('esc', 'Escritor'), ('ilu', 'Ilustrador'), ('tra', 'Traductor'), ('edi', 'Editorial')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('ley', 'Leyendo'), ('pau', 'Pausado'), ('lei', 'Leído')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bookmarklog',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('ley', 'Leyendo'), ('pau', 'Pausado'), ('lei', 'Leído')], max_length=3),
        ),
        migrations.AlterField(
            model_name='comicinvolvement',
            name='role',
            field=models.CharField(choices=[('edi', 'Editorial'), ('gui', 'Guionista'), ('dib', 'Dibujante')], max_length=3),
        ),
        migrations.AlterField(
            model_name='comicmark',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('ley', 'Leyendo'), ('pau', 'Pausado'), ('lei', 'Leído')], max_length=3),
        ),
        migrations.AlterField(
            model_name='comicmarklog',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('ley', 'Leyendo'), ('pau', 'Pausado'), ('lei', 'Leído')], max_length=3),
        ),
        migrations.AlterField(
            model_name='comicseriesinvolvement',
            name='role',
            field=models.CharField(choices=[('edi', 'Editorial'), ('gui', 'Guionista'), ('dib', 'Dibujante')], max_length=3),
        ),
        migrations.AlterField(
            model_name='comicseriesmark',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('sig', 'Siguiendo'), ('pau', 'Pausado'), ('fin', 'Finalizado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='comicseriesmarklog',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('sig', 'Siguiendo'), ('pau', 'Pausado'), ('fin', 'Finalizado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dlcinvolvement',
            name='role',
            field=models.CharField(choices=[('des', 'Desarrollador'), ('dis', 'Distribuidor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dlcmark',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('jug', 'Jugando'), ('pau', 'Pausado'), ('ter', 'Terminado'), ('com', 'Completado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dlcmarklog',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('jug', 'Jugando'), ('pau', 'Pausado'), ('ter', 'Terminado'), ('com', 'Completado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='gameinvolvement',
            name='role',
            field=models.CharField(choices=[('des', 'Desarrollador'), ('dis', 'Distribuidor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='gamemark',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('jug', 'Jugando'), ('pau', 'Pausado'), ('ter', 'Terminado'), ('com', 'Completado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='gamemarklog',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('jug', 'Jugando'), ('pau', 'Pausado'), ('ter', 'Terminado'), ('com', 'Completado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('pel', 'Película'), ('cor', 'Corto'), ('doc', 'Docufilm')], default='pel', max_length=3),
        ),
        migrations.AlterField(
            model_name='movieinvolvement',
            name='role',
            field=models.CharField(choices=[('pra', 'Productora'), ('dis', 'Distribuidora'), ('pro', 'Productor'), ('dir', 'Director'), ('gui', 'Guionista'), ('act', 'Actor'), ('pre', 'Presentador')], max_length=3),
        ),
        migrations.AlterField(
            model_name='moviemark',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('vis', 'Visto')], max_length=3),
        ),
        migrations.AlterField(
            model_name='moviemarklog',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('vis', 'Visto')], max_length=3),
        ),
        migrations.AlterField(
            model_name='series',
            name='category',
            field=models.CharField(choices=[('ser', 'Serie'), ('min', 'Miniserie'), ('pro', 'Programa TV'), ('doc', 'Documental')], default='ser', max_length=3),
        ),
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('emi', 'En emisión'), ('can', 'Cancelado'), ('fin', 'Finalizado'), ('esp', 'A espera de nueva temporada')], default='emi', max_length=3),
        ),
        migrations.AlterField(
            model_name='seriesinvolvement',
            name='role',
            field=models.CharField(choices=[('pra', 'Productora'), ('dis', 'Distribuidora'), ('pro', 'Productor'), ('dir', 'Director'), ('gui', 'Guionista'), ('act', 'Actor'), ('pre', 'Presentador')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seriesmark',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('sig', 'Siguiendo'), ('pau', 'Pausado'), ('fin', 'Finalizado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seriesmarklog',
            name='option',
            field=models.CharField(blank=True, choices=[('pen', 'Pendiente'), ('sig', 'Siguiendo'), ('pau', 'Pausado'), ('fin', 'Finalizado')], max_length=3),
        ),
    ]
