# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20200522_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comicseries',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
